-- ZonaGTA6TV V1 - Supabase
create extension if not exists pgcrypto;

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 username text unique not null check (username ~ '^[a-z0-9_]{3,24}$'),
 first_name text default '',
 last_name text default '',
 birth_date date,
 country text,
 avatar_url text,
 bio text default '',
 created_at timestamptz default now()
);
create table if not exists public.posts (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 body text not null check (char_length(body) between 1 and 2000),
 created_at timestamptz default now()
);
create table if not exists public.comments (
 id bigint generated by default as identity primary key,
 post_id bigint not null references public.posts(id) on delete cascade,
 user_id uuid not null references public.profiles(id) on delete cascade,
 body text not null check (char_length(body) between 1 and 500),
 created_at timestamptz default now()
);
create table if not exists public.likes (
 post_id bigint not null references public.posts(id) on delete cascade,
 user_id uuid not null references public.profiles(id) on delete cascade,
 created_at timestamptz default now(),
 primary key(post_id,user_id)
);
create table if not exists public.follows (
 follower_id uuid not null references public.profiles(id) on delete cascade,
 following_id uuid not null references public.profiles(id) on delete cascade,
 created_at timestamptz default now(),
 primary key(follower_id,following_id),
 check(follower_id<>following_id)
);
create table if not exists public.messages (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 room text not null default 'general',
 body text not null check (char_length(body) between 1 and 500),
 created_at timestamptz default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
declare base_username text; candidate text; n int:=0;
begin
 base_username:=lower(regexp_replace(coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)),'[^a-z0-9_]','','g'));
 if char_length(base_username)<3 then base_username:='usuario'; end if;
 candidate:=left(base_username,24);
 while exists(select 1 from public.profiles where username=candidate) loop
   n:=n+1; candidate:=left(base_username,20)||n::text;
 end loop;
 insert into public.profiles(id,username,first_name,last_name,birth_date,country)
 values(new.id,candidate,coalesce(new.raw_user_meta_data->>'first_name',''),coalesce(new.raw_user_meta_data->>'last_name',''),nullif(new.raw_user_meta_data->>'birth_date','')::date,new.raw_user_meta_data->>'country')
 on conflict(id) do nothing;
 return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;
alter table public.follows enable row level security;
alter table public.messages enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select using (true);
drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert with check(auth.uid()=id);
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update using(auth.uid()=id);

drop policy if exists posts_select on public.posts;
create policy posts_select on public.posts for select using(true);
drop policy if exists posts_insert on public.posts;
create policy posts_insert on public.posts for insert with check(auth.uid()=user_id);
drop policy if exists posts_update on public.posts;
create policy posts_update on public.posts for update using(auth.uid()=user_id);
drop policy if exists posts_delete on public.posts;
create policy posts_delete on public.posts for delete using(auth.uid()=user_id);

drop policy if exists comments_select on public.comments;
create policy comments_select on public.comments for select using(true);
drop policy if exists comments_insert on public.comments;
create policy comments_insert on public.comments for insert with check(auth.uid()=user_id);
drop policy if exists comments_delete on public.comments;
create policy comments_delete on public.comments for delete using(auth.uid()=user_id);

drop policy if exists likes_select on public.likes;
create policy likes_select on public.likes for select using(true);
drop policy if exists likes_insert on public.likes;
create policy likes_insert on public.likes for insert with check(auth.uid()=user_id);
drop policy if exists likes_delete on public.likes;
create policy likes_delete on public.likes for delete using(auth.uid()=user_id);

drop policy if exists follows_select on public.follows;
create policy follows_select on public.follows for select using(true);
drop policy if exists follows_insert on public.follows;
create policy follows_insert on public.follows for insert with check(auth.uid()=follower_id);
drop policy if exists follows_delete on public.follows;
create policy follows_delete on public.follows for delete using(auth.uid()=follower_id);

drop policy if exists messages_select on public.messages;
create policy messages_select on public.messages for select to authenticated using(true);
drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert to authenticated with check(auth.uid()=user_id);

-- Realtime: en Dashboard > Database > Replication habilita posts, comments y messages.
