-- ZonaGTA6TV V1.1 — esquema Supabase
create extension if not exists pgcrypto;

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 username text unique not null check (char_length(username) between 3 and 24),
 first_name text, last_name text, birth_date date, country text, bio text default '',
 avatar_url text,
 created_at timestamptz default now()
);
create table if not exists public.posts (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 body text not null check (char_length(body) between 1 and 2000),
 image_url text,
 created_at timestamptz default now()
);
create table if not exists public.comments (
 id bigint generated by default as identity primary key,
 post_id bigint not null references public.posts(id) on delete cascade,
 user_id uuid not null references public.profiles(id) on delete cascade,
 body text not null check (char_length(body) between 1 and 1000),
 created_at timestamptz default now()
);
create table if not exists public.likes (
 post_id bigint references public.posts(id) on delete cascade,
 user_id uuid references public.profiles(id) on delete cascade,
 created_at timestamptz default now(),
 primary key(post_id,user_id)
);
create table if not exists public.follows (
 follower_id uuid references public.profiles(id) on delete cascade,
 following_id uuid references public.profiles(id) on delete cascade,
 created_at timestamptz default now(),
 primary key(follower_id,following_id),
 check(follower_id <> following_id)
);
create table if not exists public.messages (
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 room text not null default 'general',
 body text not null check (char_length(body) between 1 and 1000),
 created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;
alter table public.follows enable row level security;
alter table public.messages enable row level security;

create policy "profiles_select" on public.profiles for select using (true);
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid()=id);
create policy "profiles_update_own" on public.profiles for update using (auth.uid()=id);

create policy "posts_select" on public.posts for select using (true);
create policy "posts_insert_auth" on public.posts for insert with check (auth.uid()=user_id);
create policy "posts_update_own" on public.posts for update using (auth.uid()=user_id);
create policy "posts_delete_own" on public.posts for delete using (auth.uid()=user_id);

create policy "comments_select" on public.comments for select using (true);
create policy "comments_insert_auth" on public.comments for insert with check (auth.uid()=user_id);
create policy "comments_update_own" on public.comments for update using (auth.uid()=user_id);
create policy "comments_delete_own" on public.comments for delete using (auth.uid()=user_id);

create policy "likes_select" on public.likes for select using (true);
create policy "likes_insert_own" on public.likes for insert with check (auth.uid()=user_id);
create policy "likes_delete_own" on public.likes for delete using (auth.uid()=user_id);

create policy "follows_select" on public.follows for select using (true);
create policy "follows_insert_own" on public.follows for insert with check (auth.uid()=follower_id);
create policy "follows_delete_own" on public.follows for delete using (auth.uid()=follower_id);

create policy "messages_select" on public.messages for select using (true);
create policy "messages_insert_auth" on public.messages for insert with check (auth.uid()=user_id);

-- Trigger: crea automáticamente el perfil al registrarse con email/Google.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
 insert into public.profiles(id,username,first_name,last_name,birth_date,country,bio)
 values(
   new.id,
   coalesce(nullif(new.raw_user_meta_data->>'username',''),'user_'||substr(replace(new.id::text,'-',''),1,10)),
   new.raw_user_meta_data->>'first_name',
   new.raw_user_meta_data->>'last_name',
   nullif(new.raw_user_meta_data->>'birth_date','')::date,
   new.raw_user_meta_data->>'country',
   coalesce(new.raw_user_meta_data->>'bio','')
 ) on conflict (id) do nothing;
 return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Realtime: activa estas tablas desde Database > Replication en Supabase:
-- posts, comments, likes, follows, messages.
